semi: true
singleQuote: true
jsxSingleQuote: false
arrowParens: always
trailingComma: all
printWidth: 120
tabWidth: 2
importOrder:
  - "^(?![@.]).*"
  - "^@?\\w"
  - "^@/\\w+/.*$"
  - "^[./]"
importOrderSortSpecifiers: true
importOrderSeparation: true
plugins:
  - "prettier-plugin-tailwindcss"
  - "@trivago/prettier-plugin-sort-imports"
